### ISSUE TITLE
Add to bower

### ISSUE THREAD

**Issue by mvexel** [yohanboniface/Leaflet.EditInOSM#12]
See https://github.com/yohanboniface/Leaflet.EditInOSM/pull/11 for a pull request

**Comment by yohanboniface** [comment]
Merged :)

**Comment by mvexel** [comment]
Did you commit it to bower as well? http://bower.io/docs/creating-packages/#register

Also, I don't think the license is the same as your 'do what the fuck you want' license - you may want to tweak that ;)
